In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


2.4.1


# Scalars

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

# Matrix

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]


tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

# Tensors

In [20]:
TENSOR = torch.tensor([[[[1,2,3],
                       [3,5,78],
                       [18,29,439],[33,44,67]]]])
TENSOR

tensor([[[[  1,   2,   3],
          [  3,   5,  78],
          [ 18,  29, 439],
          [ 33,  44,  67]]]])

In [21]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [22]:
TENSOR.ndim

4

In [19]:
TENSOR[0]

tensor([[  1,   2,   3],
        [  3,   5,  78],
        [ 18,  29, 439]])

# Random Tensors

In [24]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype


(tensor([[0.0479, 0.2563, 0.5650, 0.3647],
         [0.5281, 0.1895, 0.3414, 0.0137],
         [0.9009, 0.4710, 0.4051, 0.3956]]),
 torch.float32)

In [30]:
image_random_tensor = torch.rand(size=(224,224,3))
image_random_tensor.shape


torch.Size([224, 224, 3])

In [32]:
zero_tensor = torch.zeros(size=(3,3,4))
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [42]:
ones_tensor = torch.ones(size=(3,3,3))
print(ones_tensor)
print(ones_tensor.dtype)




tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.float32


In [46]:
range_tensor = torch.arange(start=0,end=11,step=1)
range_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=float)
float_32_tensor.dtype

torch.float64

In [52]:
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [61]:
first_rand = torch.rand(3,4)
first_rand

tensor([[0.6989, 0.3840, 0.6714, 0.5946],
        [0.0823, 0.3135, 0.6006, 0.2193],
        [0.4125, 0.1052, 0.8568, 0.9044]])

In [66]:
second_rand = torch.rand(1,4)
second_rand

tensor([[0.0356, 0.3099, 0.7411, 0.9715]])

In [67]:
multiply_tensor = first_rand * second_rand
multiply_tensor

tensor([[0.0249, 0.1190, 0.4975, 0.5777],
        [0.0029, 0.0971, 0.4451, 0.2131],
        [0.0147, 0.0326, 0.6350, 0.8787]])

Time stamp in video is 2hr 3mins