In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


2.4.1


# Scalars

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

# Matrix

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]


tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

# Tensors

In [20]:
TENSOR = torch.tensor([[[[1,2,3],
                       [3,5,78],
                       [18,29,439],[33,44,67]]]])
TENSOR

tensor([[[[  1,   2,   3],
          [  3,   5,  78],
          [ 18,  29, 439],
          [ 33,  44,  67]]]])

In [21]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [22]:
TENSOR.ndim

4

In [19]:
TENSOR[0]

tensor([[  1,   2,   3],
        [  3,   5,  78],
        [ 18,  29, 439]])

# Random Tensors

In [24]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype


(tensor([[0.0479, 0.2563, 0.5650, 0.3647],
         [0.5281, 0.1895, 0.3414, 0.0137],
         [0.9009, 0.4710, 0.4051, 0.3956]]),
 torch.float32)

In [30]:
image_random_tensor = torch.rand(size=(224,224,3))
image_random_tensor.shape


torch.Size([224, 224, 3])

In [32]:
zero_tensor = torch.zeros(size=(3,3,4))
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
ones_tensor = torch.ones(size=(3,3,3))
ones_tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])