In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


2.4.1


# Scalars

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

# Matrix

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]


tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

# Tensors

In [20]:
TENSOR = torch.tensor([[[[1,2,3],
                       [3,5,78],
                       [18,29,439],[33,44,67]]]])
TENSOR

tensor([[[[  1,   2,   3],
          [  3,   5,  78],
          [ 18,  29, 439],
          [ 33,  44,  67]]]])

In [21]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [22]:
TENSOR.ndim

4

In [19]:
TENSOR[0]

tensor([[  1,   2,   3],
        [  3,   5,  78],
        [ 18,  29, 439]])