In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


2.4.1


# Scalars

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

# Matrix

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]


tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

# Tensors

In [20]:
TENSOR = torch.tensor([[[[1,2,3],
                       [3,5,78],
                       [18,29,439],[33,44,67]]]])
TENSOR

tensor([[[[  1,   2,   3],
          [  3,   5,  78],
          [ 18,  29, 439],
          [ 33,  44,  67]]]])

In [21]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [22]:
TENSOR.ndim

4

In [19]:
TENSOR[0]

tensor([[  1,   2,   3],
        [  3,   5,  78],
        [ 18,  29, 439]])

# Random Tensors

In [24]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype


(tensor([[0.0479, 0.2563, 0.5650, 0.3647],
         [0.5281, 0.1895, 0.3414, 0.0137],
         [0.9009, 0.4710, 0.4051, 0.3956]]),
 torch.float32)

In [30]:
image_random_tensor = torch.rand(size=(224,224,3))
image_random_tensor.shape


torch.Size([224, 224, 3])

In [32]:
zero_tensor = torch.zeros(size=(3,3,4))
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [42]:
ones_tensor = torch.ones(size=(3,3,3))
print(ones_tensor)
print(ones_tensor.dtype)




tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.float32


In [46]:
range_tensor = torch.arange(start=0,end=11,step=1)
range_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=float)
float_32_tensor.dtype

torch.float64

In [52]:
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [61]:
first_rand = torch.rand(3,4)
first_rand

tensor([[0.6989, 0.3840, 0.6714, 0.5946],
        [0.0823, 0.3135, 0.6006, 0.2193],
        [0.4125, 0.1052, 0.8568, 0.9044]])

In [66]:
second_rand = torch.rand(1,4)
second_rand

tensor([[0.0356, 0.3099, 0.7411, 0.9715]])

In [67]:
multiply_tensor = first_rand * second_rand
multiply_tensor

tensor([[0.0249, 0.1190, 0.4975, 0.5777],
        [0.0029, 0.0971, 0.4451, 0.2131],
        [0.0147, 0.0326, 0.6350, 0.8787]])

Time stamp in video is 2hr 3mins

In [72]:
# Create a tensor
some_tensor = torch.rand(3, 4, dtype=torch.float16)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9082, 0.5332, 0.1768, 0.6724],
        [0.9443, 0.9961, 0.0830, 0.2764],
        [0.3159, 0.9429, 0.7935, 0.1445]], dtype=torch.float16)
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float16
Device tensor is stored on: cpu


In [69]:
some_tensor.size()

torch.Size([3, 4])

In [70]:
some_tensor.dtype

torch.float32

In [71]:
some_tensor.device

device(type='cpu')

In [89]:
test_tensor = torch.tensor([[1.,2.,3.]])
test_tensor + 10

tensor([[11., 12., 13.]])

In [76]:
test_tensor * 10

tensor([10, 20, 30])

In [85]:
matrix_tensor = torch.rand(3,1)
matrix_tensor.shape


torch.Size([3, 1])

In [87]:
matrix_tensor.dtype

torch.float32

In [94]:
test_tensor.shape

torch.Size([1, 3])

In [92]:
output = torch.matmul(test_tensor, matrix_tensor)
output

tensor([[3.7533]])

In [96]:
output = test_tensor @ matrix_tensor
output

tensor([[3.7533]])

In [97]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9,12]],dtype=torch.float32)

In [98]:
print(tensor_B.T)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [99]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [102]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A.T
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


Video time stamp 2hrs 48mins